version: "3"

networks:
  app-network:
    ipam:
      config:
        - subnet: 172.31.0.0/16

volumes:
  socket:
    driver: local
  log:
    driver: local
  docroot:
    driver: local

services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    networks:
      - app-network
    ports:
      - "8080:80"
    volumes:
      - ./docroot:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
  app:
    container_name: minimal_sns_app
    build: app/go
    volumes:
      - ./app/go:/app
    networks:
      - app-network
    environment:
      TZ: "Asia/Tokyo"
  db:
    image: mysql:latest
    container_name: db
    hostname: db
    networks:
      - app-network
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: app
      TZ: "Asia/Tokyo"
